"""ods_product_description

Revision ID: 295a98101466
Revises: bd0b43e78a3f
Create Date: 2022-09-22 21:15:04.659037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '295a98101466'
down_revision = 'bd0b43e78a3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ods_product_description',
    sa.Column('product_description_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('row_guid', sa.String(), nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('processed_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('product_description_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ods_product_description')
    # ### end Alembic commands ###
