"""dm_monthly_city_sales_summary

Revision ID: 309935ba867c
Revises: 5816dec4b129
Create Date: 2022-10-27 20:40:42.320756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309935ba867c'
down_revision = '5816dec4b129'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_city_sales_summary',
    sa.Column('order_year', sa.String(), nullable=False),
    sa.Column('order_month', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state_province', sa.String(), nullable=True),
    sa.Column('country_region', sa.String(), nullable=True),
    sa.Column('total_due', sa.FLOAT(), nullable=True),
    sa.Column('profit', sa.FLOAT(), nullable=True),
    sa.Column('due_growth_rate', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('order_year', 'order_month', 'city'),
    schema='dm'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_city_sales_summary', schema='dm')
    # ### end Alembic commands ###
