"""ods_product_model_product_description

Revision ID: 326894f4c94c
Revises: ffdd51f2a0ed
Create Date: 2022-10-27 19:28:36.301291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '326894f4c94c'
down_revision = 'ffdd51f2a0ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_model_product_description',
    sa.Column('product_model_id', sa.INTEGER(), nullable=False),
    sa.Column('product_description_id', sa.INTEGER(), nullable=False),
    sa.Column('culture', sa.String(), nullable=True),
    sa.Column('row_guid', sa.String(), nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('processed_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('product_model_id', 'product_description_id'),
    schema='ods'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_model_product_description', schema='ods')
    # ### end Alembic commands ###
