"""add ods schema

Revision ID: 33789139150d
Revises: 
Create Date: 2022-10-13 21:37:02.674152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33789139150d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('address_id', sa.INTEGER(), nullable=False),
    sa.Column('address_line1', sa.String(), nullable=True),
    sa.Column('address_line2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state_province', sa.String(), nullable=True),
    sa.Column('country_region', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('row_guid', sa.String(), nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('processed_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('address_id'),
    schema='ods'
    )
    op.create_table('customer',
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('name_style', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('suffix', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('sales_person', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('password_salt', sa.String(), nullable=True),
    sa.Column('row_guid', sa.String(), nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('processed_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id'),
    schema='ods'
    )
    op.create_table('customer_address',
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('address_id', sa.INTEGER(), nullable=False),
    sa.Column('address_type', sa.String(), nullable=True),
    sa.Column('row_guid', sa.String(), nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('processed_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id', 'address_id'),
    schema='ods'
    )
    op.create_table('product',
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('product_number', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('standard_cost', sa.FLOAT(), nullable=True),
    sa.Column('list_price', sa.FLOAT(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('product_category_id', sa.INTEGER(), nullable=True),
    sa.Column('product_model_id', sa.INTEGER(), nullable=True),
    sa.Column('sell_start_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('sell_end_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('discontinued_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('thumbnail_photo', sa.String(), nullable=True),
    sa.Column('thumbnail_photo_file_name', sa.String(), nullable=True),
    sa.Column('row_guid', sa.String(), nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('processed_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    schema='ods'
    )
    op.create_table('product_category',
    sa.Column('product_category_id', sa.INTEGER(), nullable=False),
    sa.Column('parent_product_category_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('row_guid', sa.String(), nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('processed_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('product_category_id'),
    schema='ods'
    )
    op.create_table('product_description',
    sa.Column('product_description_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('row_guid', sa.String(), nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('processed_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('product_description_id'),
    schema='ods'
    )
    op.create_table('product_model',
    sa.Column('product_model_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('catalog_description', sa.String(), nullable=True),
    sa.Column('row_guid', sa.String(), nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('processed_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('product_model_id'),
    schema='ods'
    )
    op.create_table('product_model_product_description',
    sa.Column('product_model_id', sa.INTEGER(), nullable=False),
    sa.Column('product_description_id', sa.INTEGER(), nullable=False),
    sa.Column('culture', sa.String(), nullable=True),
    sa.Column('row_guid', sa.String(), nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('processed_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('product_model_id', 'product_description_id'),
    schema='ods'
    )
    op.create_table('sales_order',
    sa.Column('sales_order_id', sa.INTEGER(), nullable=True),
    sa.Column('sales_order_detail_id', sa.INTEGER(), nullable=False),
    sa.Column('revision_number', sa.INTEGER(), nullable=True),
    sa.Column('order_date', sa.DATE(), nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('ship_date', sa.DATE(), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('online_order_flag', sa.Boolean(), nullable=True),
    sa.Column('sales_order_number', sa.String(), nullable=True),
    sa.Column('purchase_order_number', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('ship_to_address_id', sa.INTEGER(), nullable=True),
    sa.Column('bill_to_address_id', sa.INTEGER(), nullable=True),
    sa.Column('ship_method', sa.String(), nullable=True),
    sa.Column('credit_card_approval_code', sa.String(), nullable=True),
    sa.Column('sub_total', sa.FLOAT(), nullable=True),
    sa.Column('tax_amt', sa.FLOAT(), nullable=True),
    sa.Column('freight', sa.FLOAT(), nullable=True),
    sa.Column('total_due', sa.FLOAT(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('order_qty', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('unit_price', sa.FLOAT(), nullable=True),
    sa.Column('unit_price_discount', sa.FLOAT(), nullable=True),
    sa.Column('line_total', sa.FLOAT(), nullable=True),
    sa.Column('row_guid', sa.String(), nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('event_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('sales_order_detail_id'),
    schema='ods'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_order', schema='ods')
    op.drop_table('product_model_product_description', schema='ods')
    op.drop_table('product_model', schema='ods')
    op.drop_table('product_description', schema='ods')
    op.drop_table('product_category', schema='ods')
    op.drop_table('product', schema='ods')
    op.drop_table('customer_address', schema='ods')
    op.drop_table('customer', schema='ods')
    op.drop_table('address', schema='ods')
    # ### end Alembic commands ###
