"""ods_product

Revision ID: 3e5c88c2482c
Revises: da918765950b
Create Date: 2022-09-21 22:59:33.889175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e5c88c2482c'
down_revision = 'da918765950b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ods_product',
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('product_number', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('standard_cost', sa.FLOAT(), nullable=True),
    sa.Column('list_price', sa.FLOAT(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('product_category_id', sa.INTEGER(), nullable=True),
    sa.Column('product_model_id', sa.INTEGER(), nullable=True),
    sa.Column('sell_start_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('sell_end_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('discontinued_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('thumbnail_photo', sa.String(), nullable=True),
    sa.Column('thumbnail_photo_file_name', sa.String(), nullable=True),
    sa.Column('row_guid', sa.String(), nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('processed_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ods_product')
    # ### end Alembic commands ###
