"""ods_product_description

Revision ID: 4909cf043bc4
Revises: 04ab7124ed28
Create Date: 2022-10-27 19:27:26.318574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4909cf043bc4'
down_revision = '04ab7124ed28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_description',
    sa.Column('product_description_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('row_guid', sa.String(), nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('processed_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('product_description_id'),
    schema='ods'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_description', schema='ods')
    # ### end Alembic commands ###
