"""sales_order

Revision ID: 4f23e6219bd3
Revises: 
Create Date: 2022-09-18 20:50:28.793372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f23e6219bd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ods_sales_order',
    sa.Column('sales_order_id', sa.INTEGER(), nullable=True),
    sa.Column('sales_order_detail_id', sa.INTEGER(), nullable=False),
    sa.Column('revision_number', sa.INTEGER(), nullable=True),
    sa.Column('order_date', sa.DATE(), nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('ship_date', sa.DATE(), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('online_order_flag', sa.Boolean(), nullable=True),
    sa.Column('sales_order_number', sa.String(), nullable=True),
    sa.Column('purchase_order_number', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('ship_to_address_id', sa.INTEGER(), nullable=True),
    sa.Column('bill_to_address_id', sa.INTEGER(), nullable=True),
    sa.Column('ship_method', sa.String(), nullable=True),
    sa.Column('credit_card_approval_code', sa.String(), nullable=True),
    sa.Column('sub_total', sa.FLOAT(), nullable=True),
    sa.Column('tax_amt', sa.FLOAT(), nullable=True),
    sa.Column('freight', sa.FLOAT(), nullable=True),
    sa.Column('total_due', sa.FLOAT(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('order_qty', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('unit_price', sa.FLOAT(), nullable=True),
    sa.Column('unit_price_discount', sa.FLOAT(), nullable=True),
    sa.Column('line_total', sa.FLOAT(), nullable=True),
    sa.Column('row_guid', sa.String(), nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('event_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('sales_order_detail_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ods_sales_order')
    # ### end Alembic commands ###
