"""ods_customer_address

Revision ID: 849efaf4553c
Revises: 9270f1049721
Create Date: 2022-10-27 19:25:23.706363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '849efaf4553c'
down_revision = '9270f1049721'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_address',
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('address_id', sa.INTEGER(), nullable=False),
    sa.Column('address_type', sa.String(), nullable=True),
    sa.Column('row_guid', sa.String(), nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('processed_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id', 'address_id'),
    schema='ods'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_address', schema='ods')
    # ### end Alembic commands ###
