"""ods_customer

Revision ID: 88f93f3c8709
Revises: 326894f4c94c
Create Date: 2022-10-27 19:28:54.798026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88f93f3c8709'
down_revision = '326894f4c94c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('name_style', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('suffix', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('sales_person', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('password_salt', sa.String(), nullable=True),
    sa.Column('row_guid', sa.String(), nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('processed_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id'),
    schema='ods'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer', schema='ods')
    # ### end Alembic commands ###
