"""dw_customer_address

Revision ID: 933c2313f44b
Revises: fd04349689bb
Create Date: 2022-10-27 19:47:44.812681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '933c2313f44b'
down_revision = 'fd04349689bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_address',
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('address_id', sa.INTEGER(), nullable=False),
    sa.Column('address_type', sa.String(), nullable=True),
    sa.Column('row_guid', sa.String(), nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('processed_date', sa.DATE(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id', 'address_id'),
    schema='dw'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_address', schema='dw')
    # ### end Alembic commands ###
