"""ods_product_model_product_description

Revision ID: a3e6e6fc73b1
Revises: 6c6db4c1c6e7
Create Date: 2022-09-22 21:43:56.861516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3e6e6fc73b1'
down_revision = '6c6db4c1c6e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ods_product_model_product_description',
    sa.Column('product_model_id', sa.INTEGER(), nullable=False),
    sa.Column('product_description_id', sa.INTEGER(), nullable=False),
    sa.Column('culture', sa.String(), nullable=True),
    sa.Column('row_guid', sa.String(), nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('processed_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('product_model_id', 'product_description_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ods_product_model_product_description')
    # ### end Alembic commands ###
