"""ods_product_category

Revision ID: bd0b43e78a3f
Revises: 3e5c88c2482c
Create Date: 2022-09-22 09:00:26.570071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd0b43e78a3f'
down_revision = '3e5c88c2482c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ods_product_category',
    sa.Column('product_category_id', sa.INTEGER(), nullable=False),
    sa.Column('parent_product_category_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('row_guid', sa.String(), nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('processed_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('product_category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ods_product_category')
    # ### end Alembic commands ###
