"""dm_product_profit_weekly_top10

Revision ID: d34af4b57bbf
Revises: 309935ba867c
Create Date: 2022-10-27 21:02:12.386211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd34af4b57bbf'
down_revision = '309935ba867c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_profit_weekly_top10',
    sa.Column('order_year', sa.String(), nullable=False),
    sa.Column('order_week_of_year', sa.String(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('standard_cost', sa.FLOAT(), nullable=True),
    sa.Column('list_price', sa.FLOAT(), nullable=True),
    sa.Column('rank', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('order_year', 'order_week_of_year', 'product_id'),
    schema='dm'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_profit_weekly_top10', schema='dm')
    # ### end Alembic commands ###
