"""dm_shipped_order_duration_top10

Revision ID: e47b0841b1eb
Revises: d34af4b57bbf
Create Date: 2022-10-27 21:26:35.799597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e47b0841b1eb'
down_revision = 'd34af4b57bbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipped_order_duration_top10',
    sa.Column('sales_order_id', sa.INTEGER(), nullable=False),
    sa.Column('sales_order_number', sa.String(), nullable=True),
    sa.Column('ship_to_city', sa.String(), nullable=True),
    sa.Column('ship_to_province', sa.String(), nullable=True),
    sa.Column('ship_to_country_region', sa.String(), nullable=True),
    sa.Column('ship_to_postal_code', sa.String(), nullable=True),
    sa.Column('order_date', sa.DATE(), nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('rank', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('sales_order_id'),
    schema='dm'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipped_order_duration_top10', schema='dm')
    # ### end Alembic commands ###
