"""ods_product_model

Revision ID: ffdd51f2a0ed
Revises: 4909cf043bc4
Create Date: 2022-10-27 19:27:52.159596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ffdd51f2a0ed'
down_revision = '4909cf043bc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_model',
    sa.Column('product_model_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('catalog_description', sa.String(), nullable=True),
    sa.Column('row_guid', sa.String(), nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('processed_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('product_model_id'),
    schema='ods'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_model', schema='ods')
    # ### end Alembic commands ###
